import { chromium } from "playwright";
const errs=[];
const b = await chromium.launch({ executablePath:"/opt/pw-browsers/chromium" });
const p = await b.newPage();
p.on("console", m=>{ if(m.type()==="error" && !m.text().includes("404")) errs.push(m.text()); });
p.on("pageerror", e=>errs.push("PAGEERR: "+e.message));
async function dismissTalk(){ if(await p.isVisible("#talkOverlay").catch(()=>0)){ await p.click(".talk-tone"); await p.waitForTimeout(60); await p.click("#talkContinue"); await p.waitForTimeout(60);} }
await p.goto("http://localhost:4173/", { waitUntil:"networkidle" });
await p.click(".club-card"); await p.waitForTimeout(150);
await p.click("#playRound"); await p.waitForTimeout(150);
if(await p.isVisible("#kickOffBtn")) await p.click("#kickOffBtn"); await p.waitForTimeout(200);
await dismissTalk();
if(await p.isVisible("#simMatch")) await p.click("#simMatch"); await p.waitForTimeout(200);
if(await p.isVisible("#backToSeason")) await p.click("#backToSeason"); await p.waitForTimeout(150);
await dismissTalk(); await p.waitForTimeout(200);
const note = await p.$eval(".snub-note", e=> e.classList.contains("hidden")?"(hidden)":e.textContent).catch(()=>"(none)");
console.log("dressing-room note:", note);
console.log("has MoM:", /Man of the match/.test(note));
console.log("errors:", errs.length?JSON.stringify(errs):"NONE");
await b.close();
