import { chromium } from "playwright";
const errs=[];
const b = await chromium.launch({ executablePath:"/opt/pw-browsers/chromium" });
const p = await b.newPage();
p.on("console", m=>{ if(m.type()==="error" && !m.text().includes("404")) errs.push(m.text()); });
p.on("pageerror", e=>errs.push("PAGEERR: "+e.message));
await p.goto("http://localhost:4173/", { waitUntil:"networkidle" });
const cards=await p.$$(".club-card"); await cards[0].click(); await p.waitForTimeout(150);
await p.click("#openTacticsFromSeason"); await p.waitForTimeout(150);
const calls=await p.$$eval("#setPieceCalls button",e=>e.map(x=>x.textContent));
const heads=await p.$$eval(".callgroup-head",e=>e.map(x=>x.textContent));
console.log("set-piece groups:", JSON.stringify(heads));
console.log("call buttons:", JSON.stringify(calls));
// click "Pushover" and "Short line"
await p.click("button[data-call='scrumCall:pushover']"); await p.waitForTimeout(80);
await p.click("button[data-call='lineoutThrow:short']"); await p.waitForTimeout(80);
const active=await p.$$eval("#setPieceCalls button.active",e=>e.map(x=>x.textContent));
console.log("active calls after select:", JSON.stringify(active));
console.log("errors:", errs.length?JSON.stringify(errs):"NONE");
await b.close();
